services:
  api:
    build:
      context: ./service/backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./service/backend:/app
    depends_on:
      - db
    networks:
      - relay-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - relay-network

  whatsapp-worker:
    build:
      context: ./service/workers/whatsapp
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - whatsapp_auth:/app/.wwebjs_auth
    depends_on:
      - db
    networks:
      - relay-network

volumes:
  postgres_data:
  whatsapp_auth:

networks:
  relay-network:
