"""init schema

Revision ID: ee92b9e4e79f
Revises: 0001_baseline
Create Date: 2026-02-18 16:26:37.559213
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ee92b9e4e79f'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'send_logs', 'sender_accounts', ['sender_account_id'], ['id'])
    op.create_foreign_key(None, 'template_variables', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'worker_states', 'campaigns', ['current_campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_states', type_='foreignkey')
    op.drop_constraint(None, 'template_variables', type_='foreignkey')
    op.drop_constraint(None, 'send_logs', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
